#define TAP_CODE_DELAY 25

// #define PALETTEFX_ENABLE_ALL_EFFECTS
// #define PALETTEFX_ENABLE_ALL_PALETTES

#define PALETTEFX_GRADIENT_ENABLE
#define PALETTEFX_FLOW_ENABLE
// #define PALETTEFX_RIPPLE_ENABLE
// #define PALETTEFX_SPARKLE_ENABLE
#define PALETTEFX_VORTEX_ENABLE
// #define PALETTEFX_REACTIVE_ENABLE

#define PALETTEFX_AFTERBURN_ENABLE
#define PALETTEFX_AMBER_ENABLE
// #define PALETTEFX_BADWOLF_ENABLE
#define PALETTEFX_CARNIVAL_ENABLE
#define PALETTEFX_CLASSIC_ENABLE
#define PALETTEFX_DRACULA_ENABLE
// #define PALETTEFX_GROOVY_ENABLE
// #define PALETTEFX_NOTPINK_ENABLE
#define PALETTEFX_PHOSPHOR_ENABLE
#define PALETTEFX_POLARIZED_ENABLE
#define PALETTEFX_ROSEGOLD_ENABLE
#define PALETTEFX_SPORT_ENABLE
#define PALETTEFX_SYNTHWAVE_ENABLE
#define PALETTEFX_THERMAL_ENABLE
#define PALETTEFX_VIRIDIS_ENABLE
// #define PALETTEFX_WATERMELON_ENABLE

#define NKRO_DEFAULT_ON false
